webserver/config/routes.rb
Webserver::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :submissions, except: [:show, :edit, :update, :destroy] do
    member do
      get 'download'
    end
  end

  resources :courses do
    member do
      post 'create_section'
      delete 'delete_section/:section_id', to: 'courses#delete_section', as: 'delete_section'
      post 'add_ta'
      delete 'remove_ta/:ta_id', to: 'courses#remove_ta', as: 'remove_ta'
    end
    resources :assignments, except: [:index] do
      member do
        get 'collect'
      end
    end
  end
end

webserver/app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :course
  has_many :submissions, dependent: :destroy
  validates :course, :name, :due_date, presence: true

  # Courses may not have multiple assignments with the same name
  validates :name, uniqueness: { scope: :course_id }

  def pretty_due_date
    return nil if self.due_date.nil?
    self.due_date.to_s(:pretty)
  end
end

webserver/app/controllers/assignments_controller.rb
require 'zip'

class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy, :collect]
  before_action :set_course

  def collect # collect submissions

    # Folder hierarchy is:
    # course > section > assignment label > student pawprint > attemptnum_LATE?_submittime > files
    base_folder = @course.name + '/'
    base_folder << "<SECTIONREPLACEME>/"
    base_folder << @assignment.name + '/'

    filename = @assignment.name + '_submissions_' + Time.zone.now.to_s

    zip_file = Tempfile.new(filename)
    begin
      # Initialize temp file as zip
      # Add files to the zip
      Zip::OutputStream.open(zip_file) do |zos|
        @assignment.submissions.each do |submission|
          submission.submission_files.each do |file|

            # Build current folder
            current_folder = base_folder.gsub('<SECTIONREPLACEME>', submission.section.name)
            current_folder << submission.user.pawprint + '/'
            current_folder << 'attempt' + submission.attempt_number.to_s + '_'
            current_folder << 'LATE_' if @assignment.due_date <  submission.created_at
            current_folder << submission.created_at.to_s + '/'

            zos.put_next_entry(current_folder + file.filename)
            zos.print(file.file_contents)
          end
        end
      end

      zip_data = File.read(zip_file.path)

      # Send data to the browser
      send_data(zip_data, type: 'application/zip', filename: filename)
    ensure
      # close and delete tempfile
      zip_file.close
      zip_file.unlink
    end



  end

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)
    @assignment.course = @course

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to course_path(@course), notice: 'Assignment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @assignment }
      else
        format.html { render action: 'new' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to course_path(@course), notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to course_path(@course) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    def set_course
      @course = Course.find(params[:course_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      p = params.require(:assignment).permit(:name, :due_date)
      if p[:due_date]
        dd = ActiveSupport::TimeWithZone.new(nil, Time.zone, Time.strptime(p[:due_date], '%m/%d/%Y %H:%M %p'))
      end
      p[:due_date] = dd
      return p
    end
end

webserver/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

webserver/app/views/assignments/_form.html.erb
<%= simple_form_for [@course, @assignment] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-4">
        <%= f.input :name %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <%= f.input :due_date, as: :string do %>
          <div class="input-group date" id="datetimepicker1">
            <%= f.input_field :due_date, as: :string, value: localize(f.object.due_date || Time.zone.now, format: '%m/%d/%Y %I:%M %p') %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
  <br>
<% end %>


<script>
  var ready = function() {
    $('#datetimepicker1').datetimepicker();
  };

  $(document).ready(ready);
  $(document).on('page:load', ready);
</script>

webserver/app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', course_assignment_path(@course, @assignment) %> |
<%= link_to 'Back', course_path(@course) %>

webserver/app/views/assignments/index.html.erb
<h1>Listing assignments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.name %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', new_assignment_path %>

webserver/app/views/assignments/new.html.erb
<h1>New assignment for <%= @course.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', course_path(@course) %>

webserver/app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assignment.name %>
</p>
<p>
  <strong>Due Date:</strong>
  <%= @assignment.due_date %>
</p>

<%= link_to 'Edit', edit_course_assignment_path(@course, @assignment) %> |
<%= link_to 'Back', course_path(@course) %>