webserver/config/routes.rb
Webserver::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :submissions, except: [:show, :edit, :update, :destroy] do
    member do
      get 'download'
    end
  end

  resources :courses do
    member do
      post 'create_section'
      delete 'delete_section/:section_id', to: 'courses#delete_section', as: 'delete_section'
      post 'add_ta'
      delete 'remove_ta/:ta_id', to: 'courses#remove_ta', as: 'remove_ta'
    end
    resources :assignments, except: [:index] do
      member do
        get 'collect'
      end
    end
  end
end

webserver/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

webserver/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: "navbar-brand #{current_page?(root_path) ? 'active' : ''}" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>

      <div class="navbar-right navbar-form">
        <% if user_signed_in? %>
          <%= button_to 'Log out', destroy_user_session_path, method: 'delete', class: 'btn btn-success'%>
        <% else %>
          <%= form_tag(new_user_session_path, method: 'POST') do %>
            <div class="form-group">
              <%= text_field_tag 'user[pawprint]', nil, placeholder:'Pawprint', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= password_field_tag 'user[password]', nil, placeholder:'Password', class: 'form-control' %>
            </div>
            <%= submit_tag "Sign in", class:'btn btn-success'%>
          <% end %>
        <% end %>
      </div>


    </div>
  </div>
</nav>

webserver/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <% if current_user.instructor? %>
    <li><%= nav_link 'Courses', courses_path %></li>
  <% end %>
  <% if current_user.ta? %>
    <li><%= nav_link 'Courses', courses_path %></li>
  <% end %>
  <% if current_user.student? %>
    <li><%= nav_link 'Submit an Assignment', new_submission_path %></li>
    <li><%= nav_link 'Your Previous Submissions', submissions_path %></li>
  <% end %>
<% end %>

webserver/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + " | Mizzou Computer Science Submission System" : "Mizzou Computer Science Submission System" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Webserver" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <div class="container">
         <%= render 'layouts/messages' %>
         <%= yield %>
       </div>
    </main>
  </body>
</html>