webserver/config/routes.rb
Webserver::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :submissions, except: [:show, :edit, :update, :destroy] do
    member do
      get 'download'
    end
  end

  resources :courses do
    member do
      post 'create_section'
      delete 'delete_section/:section_id', to: 'courses#delete_section', as: 'delete_section'
      post 'add_ta'
      delete 'remove_ta/:ta_id', to: 'courses#remove_ta', as: 'remove_ta'
    end
    resources :assignments, except: [:index] do
      member do
        get 'collect'
      end
    end
  end
end

webserver/app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :assignment
  has_one :course, through: :assignment
  belongs_to :section
  has_many :submission_files

  after_save :save_files

  validate :files_size_under_five_mb
  validate :saved_assignment_and_section

  validates :ip_address, :user, presence: true

  def initialize(params = {})
    if params.length > 0
      @files = params.delete(:file) || []
      @course_name = params.delete(:course_name)
      @assignment_name = params.delete(:assignment_name)
      @section_name = params.delete(:section_name)
    end
    super
  end

  # For simple form
  attr_accessor :assignment_name, :section_name, :course_name

  # Gets submission attempt number
  def attempt_number
    other_submissions = Submission.where(user: self.user, assignment: self.assignment).order(:created_at)
    other_submissions.map(&:id).index(self.id) + 1
  end

  private

    def saved_assignment_and_section

      c = Course.where(name: @course_name).first

      if c.nil?
        errors.add(:course_name, 'Could not find course with that name')
        return
      end

      # save and associate assignment and section
      a = c.assignments.where(name: @assignment_name).first
      if a.nil?
        errors.add(:assignment_name, 'Could not find assignment with that name.')
        return
      end
      self.assignment = a

      s = c.sections.where(name: @section_name).first
      if s.nil?
        errors.add(:section_name, 'Could not find section with that name.')
        return
      end
      self.section = s

    end

    def save_files
      # Only save if there is a file to save

      appended_file_contents = '' # For receipt token
      if @files && @files.count > 0
        @files.each do |file|
          f = SubmissionFile.new
          f.filename = sanitize_filename(file.original_filename)
          f.content_type = file.content_type
          f.file_contents = file.read
          appended_file_contents << f.file_contents
          f.submission_id = self.id
          f.save!
        end
      end
      receipt = Digest::MD5.hexdigest(appended_file_contents)
      self.update_columns(receipt: receipt)
    end

    def sanitize_filename(filename)
      # Just get filename in case of IE
      File.basename(filename)
    end


    def files_size_under_five_mb
      @files.each do |file|
        # 1048576 is the number of bytes in a megabyte
        if (file.size.to_f / 1048576) > 5
          errors.add(:file, 'File size cannot be over 5 MB')
        end
      end
    end

end

webserver/app/controllers/submissions_controller.rb
require 'zip'
require 'mizzou_ldap'

class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:download]

  # Students only for web UI
  before_filter :students_only!, except: [:create]

  # No CSRF on submission for the command line system
  skip_before_filter :verify_authenticity_token, :only => [:create]

  # Downloads a submission's files as ZIP
  def download

    # Make filename = pawprint_course_assignment_attemptnum.zip
    filename = current_user.pawprint + '_'
    filename << @submission.course.name + '_'
    filename << @submission.assignment.name + '_'
    other_submissions = Submission.where(user: current_user, assignment: @submission.assignment).order(:created_at)
    filename << "attempt"
    filename << @submission.attempt_number.to_s
    filename << '.zip'

    zip_file = Tempfile.new(filename)
    begin
      # Initialize temp file as zip
      # Add files to the zip
      Zip::OutputStream.open(zip_file) do |zos|
        @submission.submission_files.each do |file|
          zos.put_next_entry(file.filename)
          zos.print(file.file_contents)
        end
      end

      zip_data = File.read(zip_file.path)

      # Send data to the browser
      send_data(zip_data, type: 'application/zip', filename: filename)
    ensure
      # close and delete tempfile
      zip_file.close
      zip_file.unlink
    end
  end

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = current_user.submissions.order(created_at: :desc)
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # POST /submissions
  # POST /submissions.json
  def create


    # If no auth supplied and they are posting via API
    if params[:pawprint].blank? && current_user.nil?
      render json: { error: 'No pawprint supplied.' } and return
    end

    user = current_user || MizzouLdap.authenticate(params[:pawprint], params[:password])

    if user.nil?
      render json: { error: 'Failed to authenticate.  Incorrect pawprint and password.' } and return
    end

    # Can't submit as instructor
    if user.instructor?
      render json: { error: 'That user is a professor and cannot submit assignments.'} and return
    end


    @submission = Submission.new(submission_params)

    @submission.user = user
    @submission.ip_address = request.remote_ip


    respond_to do |format|
      if @submission.save
        format.html { redirect_to submissions_path, notice: 'Submission was successfully created.' }
        format.json { render action: 'show', status: :created, location: submissions_path }
      else
        format.html { render action: 'new' }
        format.json { render json: { error: @submission.errors.values.join("\n") }, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:assignment_name, :section_name, :course_name, :file => [])
    end
end

webserver/app/helpers/submissions_helper.rb
module SubmissionsHelper
end

webserver/app/views/submissions/_form.html.erb
<%= simple_form_for(@submission, html: {class: 'form-vertical', multipart: true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input 'course_name', label: 'Course Name:', required: true %>
    <%= f.input 'assignment_name', label: 'Assignment Name:', required: true %>
    <%= f.input 'section_name', label: 'Section Name:', required: true %>
    <%= f.input :file, as: :file, label: 'File to submit:', input_html: {multiple: true} %>
  </div>

  <p class="help-block">
    Submit your assignment here!
  </p>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

webserver/app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

webserver/app/views/submissions/index.html.erb
<h1>Your Previous Submissions</h1>

<div class="panel panel-default">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Course</th>
        <th>Assignment</th>
        <th>Submit Time</th>
        <th>Number of Files</th>
        <th>Receipt Token</th>
        <th>Download</th>
      </tr>
    </thead>

    <tbody>
      <% @submissions.each do |submission| %>
        <tr>
          <td><%= submission.course.name %></td>
          <td><%= submission.assignment.name %></td>
          <td><%= submission.created_at.to_s(:pretty) %></td>
          <td><%= submission.submission_files.count %></td>
          <td><%= submission.receipt %></td>
          <td><%= link_to 'Download', download_submission_path(submission), class: 'btn btn-primary' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New Submission', new_submission_path, class: 'btn btn-success' %>

webserver/app/views/submissions/new.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <h1>New submission</h1>
    <div class="center-block">
      <%= render 'form' %>
    </div>
  </div>
</div>

webserver/app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Receipt:</strong>
  <%= @submission.receipt %>
</p>

<p>
  <strong>User:</strong>
  <%= @submission.user %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @submission.ip_address %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>